### PR TITLE
Added rooms/:roomId/users query parameters to client API

### PR DESCRIPTION
**Pull request by asantibanez**
Only for Rx version.

1) Added query parameters to client api.
- q: Search query
- skip: Skip n users.
- limit: maximum number of users to return (default 30).

2) Added test dependencies
- JUnit
- Hamcrest

3) Added tests for new api. Tests available in rx/src/test/java

### CODE REVIEW

**Comment by asantibanez** [comment]
This is my first PR. I think your SDK is awesome. Would like to enhance some endpoints to complete Gitter API.

**Comment by amatkivskiy** [comment]
Hi @asantibanez. Thanks for help 👍 Additionally great thanks for adding testing to this library 👍 👍 
I have couple of notes regarding the changes:
- Have you tested that Gitter API with `skip` and `limit` params? Cause in my case this params had no influence on the response items.
- Maybe you can change the architecture of `skip`,`query` and `limit` to something like it was implemented for [ChatMessagesRequestParams](https://github.com/Gitteroid/GitterJavaSDK/blob/master/library/core/src/main/java/com/amatkivskiy/gitter/sdk/model/request/ChatMessagesRequestParams.java)?
- Regarding testing architecture: in such cases (like this library) the best way to implement integration testing is through mocking webserver calls. This makes tests more stable, quicker and there will be no need to have a private token in the tests. I've implemented such testing for `getRoomUsers(roomId)` request. Please look on the this [PR](https://github.com/Gitteroid/GitterJavaSDK/pull/13).

**Comment by asantibanez** [comment]
Thanks @amatkivskiy! I will try to implement the `skip`, `limit`, and `query` params like the architecture you have for ChatMessagesRequestParams.

Also, will look into testing locally as you suggest. I understand why local testing of the web server is better. I didn't know how to do it. Thanks for pointing out the direction.

**Comment by amatkivskiy** [comment]
@asantibanez May I close this request?

**Comment by asantibanez** [comment]
Yup. Go ahead. Great work!

**Pull request closed without merging**
