### PR TITLE
Feature/rooms users extended search

### PR DESCRIPTION
**Pull request by asantibanez**
Added Room/Users extended search parameters according to Gitter API.
- "q": searchQuery
- "skip": records to skip
- "limit": record limit

Parameters Implemented as requested using an object to encapsulate parameters. Class name is **RoomUsersRequestParams**.

Implementation added for Sync, Async and Rx libraries.

### CODE REVIEW

**Comment by asantibanez** [comment]
@amatkivskiy 

Could not add tests due to not understanding of setup of local mock server. I will be very happy to include tests. Can you point me in the right direction. Thanks?

**Comment by amatkivskiy** [comment]
@asantibanez please see PR #34 . I've extracted common gitter request parameters to separate class so it can be used for any request.

You can look on [Chat Messages request](https://github.com/Gitteroid/GitterJavaSDK/blob/dev/library/rx/src/main/java/com/amatkivskiy/gitter/sdk/rx/client/RxGitterApiClient.java#L141) as the example of passing params to the request

**Comment by amatkivskiy** [comment]
@asantibanez Any updates on this?

**Comment by amatkivskiy** [comment]
@asantibanez I am closing this PR as there is no activity for more than a year.

**Pull request closed without merging**
